import type { CachePolicy } from './types.ts';

const KiB = 1024;
const MiB = 1024 * KiB;

function policy(
  value: Omit<CachePolicy, 'version' | 'jitterRatio' | 'cacheErrors'> &
    Partial<Pick<CachePolicy, 'version' | 'jitterRatio'>>,
): CachePolicy {
  return {
    version: 1,
    jitterRatio: 0.08,
    cacheErrors: false,
    ...value,
  };
}

export const CACHE_POLICIES = {
  CONFIG_SERVER: policy({
    namespace: 'config.server',
    scope: 'system',
    freshTtlSeconds: 60,
    staleTtlSeconds: 300,
    layers: ['memory', 'shared'],
    maxEntryBytes: 2 * MiB,
    tags: ['config'],
  }),
  CONFIG_PUBLIC: policy({
    namespace: 'config.public',
    scope: 'public',
    freshTtlSeconds: 60,
    staleTtlSeconds: 300,
    layers: ['memory', 'shared', 'browser', 'cdn'],
    maxEntryBytes: 512 * KiB,
    tags: ['config'],
  }),
  PLAY_STATS: policy({
    namespace: 'play-stats',
    scope: 'system',
    freshTtlSeconds: 30,
    staleTtlSeconds: 2 * 60,
    layers: ['memory', 'shared'],
    maxEntryBytes: 16 * MiB,
    tags: ['play-stats'],
  }),
  DOUBAN_DETAILS: policy({
    namespace: 'douban.details',
    scope: 'public',
    freshTtlSeconds: 7 * 24 * 60 * 60,
    staleTtlSeconds: 24 * 60 * 60,
    negativeTtlSeconds: 30 * 60,
    layers: ['memory', 'shared', 'browser', 'cdn'],
    maxEntryBytes: 2 * MiB,
    tags: ['douban'],
  }),
  DOUBAN_HERO_BACKDROP: policy({
    namespace: 'douban.hero-backdrop',
    scope: 'public',
    freshTtlSeconds: 7 * 24 * 60 * 60,
    staleTtlSeconds: 24 * 60 * 60,
    negativeTtlSeconds: 30 * 60,
    layers: ['memory', 'shared'],
    maxEntryBytes: 64 * KiB,
    tags: ['douban'],
  }),
  DOUBAN_TRAILER: policy({
    namespace: 'douban.trailer',
    scope: 'public',
    freshTtlSeconds: 4 * 60 * 60,
    staleTtlSeconds: 30 * 60,
    negativeTtlSeconds: 5 * 60,
    layers: ['memory', 'shared'],
    maxEntryBytes: 256 * KiB,
    tags: ['douban', 'trailer'],
  }),
  DOUBAN_LIST: policy({
    namespace: 'douban.list',
    scope: 'public',
    freshTtlSeconds: 4 * 60 * 60,
    staleTtlSeconds: 60 * 60,
    negativeTtlSeconds: 2 * 60,
    layers: ['memory', 'shared', 'browser', 'cdn'],
    maxEntryBytes: 4 * MiB,
    tags: ['douban'],
  }),
  DOUBAN_CATEGORIES: policy({
    namespace: 'douban.categories',
    scope: 'public',
    freshTtlSeconds: 4 * 60 * 60,
    staleTtlSeconds: 60 * 60,
    negativeTtlSeconds: 2 * 60,
    layers: ['memory', 'shared', 'browser', 'cdn'],
    maxEntryBytes: 512 * KiB,
    tags: ['douban'],
  }),
  DOUBAN_RECOMMENDS: policy({
    namespace: 'douban.recommends',
    scope: 'public',
    freshTtlSeconds: 4 * 60 * 60,
    staleTtlSeconds: 60 * 60,
    negativeTtlSeconds: 2 * 60,
    layers: ['memory', 'shared', 'browser', 'cdn'],
    maxEntryBytes: 4 * MiB,
    tags: ['douban'],
  }),
  DOUBAN_COMMENTS: policy({
    namespace: 'douban.comments',
    scope: 'public',
    freshTtlSeconds: 60 * 60,
    staleTtlSeconds: 30 * 60,
    negativeTtlSeconds: 2 * 60,
    layers: ['memory', 'shared', 'browser', 'cdn'],
    maxEntryBytes: 2 * MiB,
    tags: ['douban'],
  }),
  DOUBAN_TOP250: policy({
    namespace: 'douban.top250',
    scope: 'public',
    freshTtlSeconds: 24 * 60 * 60,
    staleTtlSeconds: 6 * 60 * 60,
    negativeTtlSeconds: 2 * 60,
    layers: ['memory', 'shared', 'browser', 'cdn'],
    maxEntryBytes: 4 * MiB,
    tags: ['douban'],
  }),
  DOUBAN_PLATFORM_LINK: policy({
    namespace: 'douban.platform-link',
    scope: 'public',
    freshTtlSeconds: 7 * 24 * 60 * 60,
    staleTtlSeconds: 24 * 60 * 60,
    negativeTtlSeconds: 30 * 60,
    layers: ['memory', 'shared'],
    maxEntryBytes: 512 * KiB,
    tags: ['douban'],
  }),
  TMDB_ACTOR_SEARCH: policy({
    namespace: 'tmdb.actor-search',
    scope: 'public',
    freshTtlSeconds: 6 * 60 * 60,
    staleTtlSeconds: 60 * 60,
    negativeTtlSeconds: 5 * 60,
    layers: ['memory', 'shared'],
    maxEntryBytes: 2 * MiB,
    tags: ['tmdb', 'config'],
  }),
  TMDB_PERSON_DETAILS: policy({
    namespace: 'tmdb.person-details',
    scope: 'public',
    freshTtlSeconds: 24 * 60 * 60,
    staleTtlSeconds: 6 * 60 * 60,
    layers: ['memory', 'shared'],
    maxEntryBytes: 2 * MiB,
    tags: ['tmdb', 'config'],
  }),
  TMDB_MOVIE_CREDITS: policy({
    namespace: 'tmdb.movie-credits',
    scope: 'public',
    freshTtlSeconds: 12 * 60 * 60,
    staleTtlSeconds: 6 * 60 * 60,
    negativeTtlSeconds: 5 * 60,
    layers: ['memory', 'shared'],
    maxEntryBytes: 4 * MiB,
    tags: ['tmdb', 'config'],
  }),
  TMDB_TV_CREDITS: policy({
    namespace: 'tmdb.tv-credits',
    scope: 'public',
    freshTtlSeconds: 12 * 60 * 60,
    staleTtlSeconds: 6 * 60 * 60,
    negativeTtlSeconds: 5 * 60,
    layers: ['memory', 'shared'],
    maxEntryBytes: 4 * MiB,
    tags: ['tmdb', 'config'],
  }),
  TMDB_MOVIE_DETAILS: policy({
    namespace: 'tmdb.movie-details',
    scope: 'public',
    freshTtlSeconds: 24 * 60 * 60,
    staleTtlSeconds: 6 * 60 * 60,
    layers: ['memory', 'shared'],
    maxEntryBytes: 2 * MiB,
    tags: ['tmdb', 'config'],
  }),
  TMDB_TV_DETAILS: policy({
    namespace: 'tmdb.tv-details',
    scope: 'public',
    freshTtlSeconds: 24 * 60 * 60,
    staleTtlSeconds: 6 * 60 * 60,
    layers: ['memory', 'shared'],
    maxEntryBytes: 2 * MiB,
    tags: ['tmdb', 'config'],
  }),
  SHORTDRAMA_DETAILS: policy({
    namespace: 'shortdrama.details',
    scope: 'public',
    freshTtlSeconds: 4 * 60 * 60,
    staleTtlSeconds: 60 * 60,
    layers: ['memory', 'shared'],
    maxEntryBytes: 2 * MiB,
    tags: ['shortdrama'],
  }),
  SHORTDRAMA_RECOMMENDS: policy({
    namespace: 'shortdrama.recommends',
    scope: 'public',
    freshTtlSeconds: 60 * 60,
    staleTtlSeconds: 30 * 60,
    negativeTtlSeconds: 2 * 60,
    layers: ['memory', 'shared', 'browser', 'cdn'],
    maxEntryBytes: 4 * MiB,
    tags: ['shortdrama'],
  }),
  SHORTDRAMA_LIST: policy({
    namespace: 'shortdrama.list',
    scope: 'public',
    freshTtlSeconds: 2 * 60 * 60,
    staleTtlSeconds: 30 * 60,
    negativeTtlSeconds: 2 * 60,
    layers: ['memory', 'shared', 'browser', 'cdn'],
    maxEntryBytes: 4 * MiB,
    tags: ['shortdrama'],
  }),
  SHORTDRAMA_CATEGORIES: policy({
    namespace: 'shortdrama.categories',
    scope: 'public',
    freshTtlSeconds: 4 * 60 * 60,
    staleTtlSeconds: 60 * 60,
    negativeTtlSeconds: 2 * 60,
    layers: ['memory', 'shared', 'browser', 'cdn'],
    maxEntryBytes: 512 * KiB,
    tags: ['shortdrama'],
  }),
  SHORTDRAMA_SEARCH: policy({
    namespace: 'shortdrama.search',
    scope: 'public',
    freshTtlSeconds: 60 * 60,
    staleTtlSeconds: 30 * 60,
    negativeTtlSeconds: 2 * 60,
    layers: ['memory', 'shared', 'browser', 'cdn'],
    maxEntryBytes: 4 * MiB,
    tags: ['shortdrama'],
  }),
  YOUTUBE_SEARCH: policy({
    namespace: 'youtube.search',
    scope: 'system',
    freshTtlSeconds: 30 * 60,
    staleTtlSeconds: 5 * 60,
    negativeTtlSeconds: 5 * 60,
    layers: ['memory', 'shared'],
    maxEntryBytes: 4 * MiB,
    tags: ['youtube', 'config'],
  }),
  NETDISK_SEARCH: policy({
    namespace: 'netdisk.search',
    scope: 'system',
    freshTtlSeconds: 30 * 60,
    staleTtlSeconds: 5 * 60,
    negativeTtlSeconds: 2 * 60,
    layers: ['memory', 'shared'],
    maxEntryBytes: 4 * MiB,
    tags: ['netdisk', 'config'],
  }),
  SEARCH_RESULTS: policy({
    namespace: 'search.results',
    scope: 'user',
    freshTtlSeconds: 5 * 60,
    staleTtlSeconds: 2 * 60,
    negativeTtlSeconds: 60,
    layers: ['memory', 'shared'],
    maxEntryBytes: 8 * MiB,
    tags: ['search', 'sources'],
  }),
  SEARCH_SUGGESTIONS: policy({
    namespace: 'search.suggestions',
    scope: 'user',
    freshTtlSeconds: 5 * 60,
    staleTtlSeconds: 2 * 60,
    negativeTtlSeconds: 60,
    layers: ['memory', 'shared'],
    maxEntryBytes: 2 * MiB,
    tags: ['search', 'sources'],
  }),
  DANMU_NORMALIZED: policy({
    namespace: 'danmu.normalized',
    scope: 'public',
    freshTtlSeconds: 24 * 60 * 60,
    staleTtlSeconds: 6 * 60 * 60,
    negativeTtlSeconds: 5 * 60,
    layers: ['memory', 'shared'],
    maxEntryBytes: 8 * MiB,
    tags: ['danmu'],
  }),
  RELEASE_CALENDAR: policy({
    namespace: 'release-calendar',
    scope: 'public',
    freshTtlSeconds: 8 * 60 * 60,
    // Keep the last successful calendar for a week so latency-sensitive home
    // requests can always serve stale data while a refresh runs in background.
    staleTtlSeconds: 7 * 24 * 60 * 60,
    layers: ['memory', 'shared'],
    maxEntryBytes: 8 * MiB,
    tags: ['calendar'],
  }),
  BING_WALLPAPER_META: policy({
    namespace: 'bing-wallpaper.meta',
    scope: 'public',
    freshTtlSeconds: 6 * 60 * 60,
    staleTtlSeconds: 24 * 60 * 60,
    negativeTtlSeconds: 60,
    layers: ['memory', 'shared', 'browser', 'cdn'],
    maxEntryBytes: 128 * KiB,
    tags: ['wallpaper'],
  }),
  ACG_SEARCH: policy({
    namespace: 'acg.search',
    scope: 'public',
    freshTtlSeconds: 15 * 60,
    staleTtlSeconds: 5 * 60,
    negativeTtlSeconds: 2 * 60,
    layers: ['memory', 'shared'],
    maxEntryBytes: 4 * MiB,
    tags: ['acg'],
  }),
  LIVE_CHANNELS: policy({
    namespace: 'live.channels',
    scope: 'system',
    freshTtlSeconds: 10 * 60,
    staleTtlSeconds: 30 * 60,
    negativeTtlSeconds: 60,
    layers: ['memory', 'shared'],
    maxEntryBytes: 16 * MiB,
    tags: ['live', 'sources'],
  }),
  LIVE_EPG: policy({
    namespace: 'live.epg',
    scope: 'system',
    freshTtlSeconds: 15 * 60,
    staleTtlSeconds: 60 * 60,
    negativeTtlSeconds: 60,
    layers: ['memory', 'shared'],
    maxEntryBytes: 16 * MiB,
    tags: ['live', 'sources'],
  }),
  BANGUMI_PROXY: policy({
    namespace: 'bangumi.proxy',
    scope: 'public',
    freshTtlSeconds: 60 * 60,
    staleTtlSeconds: 30 * 60,
    negativeTtlSeconds: 2 * 60,
    layers: ['memory', 'shared'],
    maxEntryBytes: 4 * MiB,
    tags: ['bangumi'],
  }),
  SPIDER_JAR: policy({
    namespace: 'spider.jar',
    scope: 'system',
    freshTtlSeconds: 24 * 60 * 60,
    staleTtlSeconds: 24 * 60 * 60,
    layers: ['memory'],
    maxEntryBytes: 64 * MiB,
    tags: ['tvbox'],
  }),
  HLS_KEY: policy({
    namespace: 'hls.key',
    scope: 'user',
    freshTtlSeconds: 5 * 60,
    layers: ['memory'],
    maxEntryBytes: MiB,
    tags: ['live'],
  }),
  MEDIA_IMAGE: policy({
    namespace: 'media.image',
    scope: 'public',
    freshTtlSeconds: 7 * 24 * 60 * 60,
    layers: ['browser', 'cdn', 'disk', 'r2'],
    maxEntryBytes: 20 * MiB,
    jitterRatio: 0,
    tags: ['media'],
  }),
  MEDIA_VIDEO: policy({
    namespace: 'media.video',
    scope: 'public',
    freshTtlSeconds: 7 * 24 * 60 * 60,
    layers: ['browser', 'cdn', 'disk', 'r2'],
    maxEntryBytes: 100 * MiB,
    jitterRatio: 0,
    tags: ['media', 'trailer'],
  }),
} as const satisfies Record<string, CachePolicy>;

export type CachePolicyName = keyof typeof CACHE_POLICIES;

export const ALL_CACHE_POLICIES = Object.freeze(Object.values(CACHE_POLICIES));

const policyByNamespace = new Map(
  ALL_CACHE_POLICIES.map((value) => [value.namespace, value]),
);

export function getCachePolicy(namespace: string): CachePolicy | undefined {
  return policyByNamespace.get(namespace);
}

export function getPoliciesByTag(tag: string): CachePolicy[] {
  return ALL_CACHE_POLICIES.filter((value) => value.tags.includes(tag));
}
